# Generated by Django 3.2 on 2021-09-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_radioactivesourcesmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='radioactivesourcesmodel',
            name='acknowleged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='radioactivesourcesmodel',
            name='payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='radioactivesourcesmodel',
            name='siteVisit',
            field=models.BooleanField(default=False),
        ),
    ]
