# Generated by Django 3.2 on 2021-09-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210922_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='radioactivesourcesmodel',
            name='installation',
            field=models.BooleanField(default=False),
        ),
    ]
