# Generated by Django 3.2 on 2021-09-24 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_contactphone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
    ]
